//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCBS_Api.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BCBSEntities : DbContext
    {
        public BCBSEntities()
            : base("name=BCBSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Claim> Claims { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<SCARFSurveyAnswer> SCARFSurveyAnswers { get; set; }
        public DbSet<U65> U65 { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserCours> UserCourses { get; set; }
        public DbSet<UserMaster> UserMasters { get; set; }
    }
}
