//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCBS_Api.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claims2
    {
        public int SalesId { get; set; }
        public string WorkDayId { get; set; }
        public string LearnerName { get; set; }
        public Nullable<bool> Pre_Assm_Result { get; set; }
        public Nullable<decimal> Pre_Assm_Score_Percentage { get; set; }
        public Nullable<int> Post_Assm_Attempt { get; set; }
        public Nullable<bool> Post_Assm_Result { get; set; }
        public Nullable<decimal> Post_Assm_Score_Percentage { get; set; }
        public string Pre_Q01 { get; set; }
        public string Pre_Q02 { get; set; }
        public string Pre_Q03 { get; set; }
        public string Pre_Q04 { get; set; }
        public string Pre_Q05 { get; set; }
        public string Pre_Q06 { get; set; }
        public string Pre_Q07 { get; set; }
        public string Pre_Q08 { get; set; }
        public string Pre_Q09 { get; set; }
        public string Pre_Q10 { get; set; }
        public string Pre_Q11 { get; set; }
        public string Pre_Q12 { get; set; }
        public string Pre_Q13 { get; set; }
        public string Pre_Q14 { get; set; }
        public string Pre_Q15 { get; set; }
        public string Pre_Q16 { get; set; }
        public string Pre_Q17 { get; set; }
        public string Pre_Q18 { get; set; }
        public string Pre_Q19 { get; set; }
        public string Pre_Q20 { get; set; }
        public string Pre_Q21 { get; set; }
        public string Pre_Q22 { get; set; }
        public string Pre_Q23 { get; set; }
        public string Pre_Q24 { get; set; }
        public string Pre_Q25 { get; set; }
        public string Post_Q01 { get; set; }
        public string Post_Q02 { get; set; }
        public string Post_Q03 { get; set; }
        public string Post_Q04 { get; set; }
        public string Post_Q05 { get; set; }
        public string Post_Q06 { get; set; }
        public string Post_Q07 { get; set; }
        public string Post_Q08 { get; set; }
        public string Post_Q09 { get; set; }
        public string Post_Q10 { get; set; }
        public string Post_Q11 { get; set; }
        public string Post_Q12 { get; set; }
        public string Post_Q13 { get; set; }
        public string Post_Q14 { get; set; }
        public string Post_Q15 { get; set; }
        public string Post_Q16 { get; set; }
        public string Post_Q17 { get; set; }
        public string Post_Q18 { get; set; }
        public string Post_Q19 { get; set; }
        public string Post_Q20 { get; set; }
        public string Post_Q21 { get; set; }
        public string Post_Q22 { get; set; }
        public string Post_Q23 { get; set; }
        public string Post_Q24 { get; set; }
        public string Post_Q25 { get; set; }
        public Nullable<int> CompletionStatus { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
    }
}
