//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCBS_Api.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCARFSurveyAnswer
    {
        public int SCARFSurveyId { get; set; }
        public string WorkDayId { get; set; }
        public string LearnerName { get; set; }
        public string managerName { get; set; }
        public string managerEmailID { get; set; }
        public string Status { get; set; }
        public string StatusText { get; set; }
        public string Certainty { get; set; }
        public string CertaintyText { get; set; }
        public string Autonomy { get; set; }
        public string AutonomyText { get; set; }
        public string Relatedness { get; set; }
        public string RelatednessText { get; set; }
        public string Fairness { get; set; }
        public string FairnessText { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
    }
}
