//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCBS_Api.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class U65
    {
        public int U65_Id { get; set; }
        public string AgentName { get; set; }
        public string AgencyAddress { get; set; }
        public string AgentManagingHealth { get; set; }
        public string AgentEmail { get; set; }
        public string WorkPhoneNumber { get; set; }
        public string NationalProducerNumber { get; set; }
        public string FFMID { get; set; }
        public Nullable<decimal> AssessmentScore { get; set; }
        public Nullable<bool> PassFailStatus { get; set; }
        public Nullable<System.DateTime> DateofCompletion { get; set; }
        public string AgencyName { get; set; }
    }
}
